# Generated by Django 3.0.6 on 2020-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20200616_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs_model',
            name='operating_time',
        ),
        migrations.RemoveField(
            model_name='blogs_model',
            name='total_emp',
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='operating_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='total_emp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comapny_model',
            name='tweeter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
