# Generated by Django 3.0.6 on 2020-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_auto_20200616_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapny_model',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
