# Generated by Django 3.0.6 on 2020-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20200611_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='profile_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='tweeter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
