# Generated by Django 3.0.6 on 2020-06-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20200611_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
