# Generated by Django 3.0.6 on 2020-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_comapny_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapny_model',
            name='map_embad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
