# Generated by Django 3.0.6 on 2020-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_comapny_model_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapny_model',
            name='bg_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
